version: '3'
services:
  app:
    build: .
    ports:
      - '5500:5500'
    environment:
      - PORT=5500
    
    container_name: tyekssecurity-website
    restart: always

    links:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '2717:27017'
    volumes:
      - mongo:/data/db
volumes:
  mongo
