
[build]
  command = "npm i && npm run build"
  functions = "functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  [[redirects]]
  force = true
  from = "/app/*"
  status = 200
  to = ".netlify/functions/app/:splat"

